services:
  mongodb:
    image: mongo:latest
    container_name: vm2_mongodb
    restart: unless-stopped
    env_file:
      - ../.env
    ports:
      - "27017:27017"
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./mongodb_data:/data/db
    networks:
      - projeto_network
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.40'
        reservations:
          memory: 64M

networks:
  projeto_network:
    external: true
