services:
  wordpress:
    image: wordpress:latest
    container_name: vm2_wordpress
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "8080:80"
    env_file:
      - ../.env
    environment:
      WORDPRESS_DB_HOST: vm2_mariadb
      WORDPRESS_DB_USER: ${WP_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WP_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WP_DB_NAME}
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - projeto_network

networks:
  projeto_network:
    external: true
